[env]
TERM = "xterm-256color"

[general]
import = ["/Users/ssiyad/dotfiles/config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 14

[font.offset]
y = 1

[font.normal]
family = "GeistMono Nerd Font"

[cursor.style]
blinking = "On"
shape = "Block"

[scrolling]
history = 10000
multiplier = 3

[window]
option_as_alt = 'OnlyLeft'
