import = ["/Users/ssiyad/dotfiles/config/alacritty/catppuccin/catppuccin-mocha.toml"]

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13.5

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3
