[general]
import = ["~/.config/alacritty/acid/acid-acetic.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 9
offset.y = 6
glyph_offset.y = 3

[font.normal]
family = "GeistMono Nerd Font"

[cursor.style]
blinking = "On"
shape = "Block"

[scrolling]
history = 10000
multiplier = 3

[window]
padding.x = 6
padding.y = 6
