# Config file for i3wsr
# https://github.com/roosta/i3wsr

[icons]
# Font Awesome
TelegramDesktop = ""
firefox = ""
Alacritty = ""
Thunderbird = ""
URxvt = ""

[aliases]
# Class name aliases
TelegramDesktop = "Telegram"
firefox = "Firefox"
URxvt = "Terminal"
