monitor.alsa.rules = [
  { matches = [ { node.name = "~.*HiFi__Mic1__source"     } ]
    actions = { update-props = { node.description = "Internal Mic" } } }
  { matches = [ { node.name = "~.*HiFi__Mic2__source"     } ]
    actions = { update-props = { node.description = "Headphone Mic"  } } }
  { matches = [ { node.name = "~.*HiFi__Speaker__sink"    } ]
    actions = { update-props = { node.description = "Speaker"     } } }
  { matches = [ { node.name = "~.*HiFi__Headphones__sink" } ]
    actions = { update-props = { node.description = "Headphone"   } } }
  { matches = [ { node.name = "~.*HiFi__HDMI1__sink"      } ]
    actions = { update-props = { node.description = "HDMI 1"       } } }
  { matches = [ { node.name = "~.*HiFi__HDMI2__sink"      } ]
    actions = { update-props = { node.description = "HDMI 2"       } } }
  { matches = [ { node.name = "~.*HiFi__HDMI3__sink"      } ]
    actions = { update-props = { node.description = "HDMI 3"       } } }
]
