#!/bin/sh

~/dotfiles/git/hooks/run-local-hook commit-msg

test "" = "$(grep '^Signed-off-by: ' "$1" |
    sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
    echo >&2 Duplicate Signed-off-by lines.
    exit 1
}

WORDS=$(aspell --mode=email --add-email-quote='#' list < "$1" | sort -u)
if [ -n "$WORDS" ]; then
    printf "Possible spelling errors found in commit message:\n%s\n" "$WORDS" >&2
fi

