config.load_autoconfig()

config.source("conf/bindings.py")
config.source("conf/content.py")
config.source("conf/fonts.py")
config.source("conf/qt.py")
config.source("conf/redirects.py")
config.source("conf/scrolling.py")
config.source("conf/spellcheck.py")
config.source("conf/statusbar.py")
config.source("conf/tabs.py")
config.source("conf/theme.py")
config.source("conf/url.py")
config.source("conf/window.py")
