[Personal]
source            = imaps://sabu.siyad.p@gmail.com@imap.gmail.com
outgoing          = smtps://sabu.siyad.p@gmail.com@smtp.gmail.com
source-cred-cmd   = gopass show --password websites/accounts.google.com/sabu.siyad.p_aerc
outgoing-cred-cmd = gopass show --password websites/accounts.google.com/sabu.siyad.p_aerc
check-mail        = 5m
folder-map        = ~/.config/aerc/folder-map-personal
folders-sort      = Important, Inbox, Drafts, Sent, Trash
default           = Inbox
postpone          = Drafts
copy-to           = Sent
from              = Sabu Siyad <hello@ssiyad.com>
use-labels        = true
cache-state       = true
cache-headers     = true
cache-blobs       = false
signature-file    = ~/.config/aerc/signature-personal

[Frappe]
source            = imaps://sabu@frappe.io@inbound.frappemail.com
outgoing          = smtps://sabu@frappe.io@mail.frappemail.com
source-cred-cmd   = gopass show --password websites/frappemail.com/sabu@frappe.io
outgoing-cred-cmd = gopass show --password websites/frappemail.com/sabu@frappe.io
check-mail        = 5m
folder-map        = ~/.config/aerc/folder-map-frappe
folders-sort      = Inbox, Drafts, Sent, Trash
default           = Inbox
postpone          = Drafts
from              = Sabu Siyad <sabu@frappe.io>
use-labels        = true
cache-state       = true
cache-headers     = true
cache-blobs       = false
signature-file    = ~/.config/aerc/signature-frappe
